### PR TITLE
Bugfix: ensure thumbnail freshness and fix user navigation

### LINKED ISSUE #228: Social: fix goBack navigation between profiles

### PR DESCRIPTION
**Pull request by robertaleG**
# Description

This small PR fixes issues with images not always being up to date and reloaded in user items (user bottom sheets, search items, etc).  I also had the opportunity to fix navigation bugs with user profile back navigation.

Fixes #228 and #198

The commit history is populated by the PR #226 because I already fixed flashcard image reloading in that PR before it was merged, and wished to pull that code to widen the fix's reach to fix all images (user items and flashcard images).

The commits of this PR effectively start from commit `bd3b08dc0900c9785470eeb61552cbcc4018d892`.

# How Has This Been Tested?

No further tests, as this is a bug fixing PR. All current tests pass and coverage is still good.
  
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged in downstream modules, no conflicts with main

### CODE REVIEW

File: app/src/main/java/com/github/onlynotesswent/ui/common/ImageComposables.kt [hunk 1]
```diff
@@ -112,33 +111,28 @@ fun NonModifiableProfilePicture(
     fileViewModel: FileViewModel,
     size: Int = 150,
     testTag: String = "profilePicture",
-    onClick: () -> Unit = doesNothing
+    onClick: (() -> Unit)? = null
```
Comment (Roshan-y) [inline app/src/main/java/com/github/onlynotesswent/ui/common/ImageComposables.kt:114]: Replacing onClick to be nullable and removing the doesNothing makes the code cleaner, nice.

File: app/src/main/java/com/github/onlynotesswent/ui/common/ImageComposables.kt [hunk 2]
```diff
@@ -112,33 +111,28 @@ fun NonModifiableProfilePicture(
...
-          // Load the profile picture if it exists
+        if (compareUID(
+            profilePictureUri.value, user.value?.uid, FileType.PROFILE_PIC_JPEG.fileExtension)) {
           rememberAsyncImagePainter(profilePictureUri.value)
         } else {
-          // Load the default profile picture if it doesn't exist
+          // Load the default profile picture if no picture was found
+          // and download the profile picture if it should exist
+          if (user.value?.hasProfilePicture == true) {
+            fileViewModel.downloadFile(
```
Comment (Roshan-y) [inline app/src/main/java/com/github/onlynotesswent/ui/common/ImageComposables.kt:126]: Nice job changing it to only download when no image is found

File: app/src/main/java/com/github/onlynotesswent/ui/search/Search.kt [hunk 3]
```diff
@@ -380,8 +381,9 @@ fun SearchScreen(
               contentPadding = PaddingValues(horizontal = 16.dp),
               modifier = Modifier.fillMaxWidth().padding(padding).testTag("filteredUserList")) {
                 items(filteredUsers.value.size) { index ->
+                  val userState = remember { derivedStateOf { filteredUsers.value[index] } }
```
Comment (Roshan-y) [inline app/src/main/java/com/github/onlynotesswent/ui/search/Search.kt:384]: nice use of state to make sure it recomposes

File: app/src/main/java/com/github/onlynotesswent/ui/user/PublicProfile.kt [hunk 4]
```diff
@@ -593,7 +594,7 @@ fun UserBottomSheet(
  */
 @Composable
 fun UserItem(
-    user: User,
+    user: State<User>,
```
Comment (Roshan-y) [inline app/src/main/java/com/github/onlynotesswent/ui/user/PublicProfile.kt:597]: Again nice use of state to make sure it recomposes the item properly

**Review by Roshan-y — APPROVED** [review]
Nice job changing the appropriate parts of the code to properly recompose the profile picture in the search user screen
